### PR TITLE
fix: locale selection clickable for mobile

### PR DESCRIPTION
**Pull request by CodesDoWork**

### CODE REVIEW

**Comment by Benjamin-Frost** [comment]
I tested this on my mac on Safari, and the issue still seems to remain: I can't open the language dropdown

**Comment by Benjamin-Frost** [comment]
Using `onclick` seems to be an issue in many browsers. Astro instead recommends to use a script to attach an `EventListener`. See [this](https://docs.astro.build/de/guides/client-side-scripts/#handle-onclick-and-other-events) for reference. I quickly tested this, and the button now seems to respond to the clicks on mac.

We should probably refactor all `onclick` of our page to use `EventListener`s instead.

**Comment by CodesDoWork** [comment]
@Benjamin-Frost can you check the new approach? It's hard to test Mobile behavior here.

**Comment by Benjamin-Frost** [comment]
Still no luck :/ One issue is that you add an `EventListener` to the element with id `open-dropdown-${id}`, which does not exist. Your button has a class of this name but does not have this id. However, even after fixing this Safari does not seem to like the dropdown. I can see in the HTML that the `ul` receives the class `focus` but it doesn't seem to change anything. Maybe we misused `peer-focus`?

**Review by Benjamin-Frost — APPROVED** [review]
That did the trick 👍

**Pull request merged**
