### PR TITLE
Revert "Added team data"

### PR DESCRIPTION
**Pull request by styrix560**
Reverts blz-it/blz-it.de#299

### CODE REVIEW

**Comment by styrix560** [comment]
For some reason in prod the wwhole page breaks

**Comment by styrix560** [comment]
Skill names are now [object Object] which is fair enough, because I just assumed if there are no type errors then everything should be fine. I have no idea why the images are broken.

**Comment by styrix560** [comment]
If you approve of these changes, please merge it also. I will take a look at it (and hope I dont have to do it the Astro-way because that one sucks) when I have time tomorrow.

**Comment by Benjamin-Frost** [comment]
> Skill names are now [object Object] which is fair enough, because I just assumed if there are no type errors then everything should be fine. I have no idea why the images are broken.

This should be an easy fix. You used `/src/assets/img/team/x` as image paths which doesn't exist after building. Does this help?

- https://docs.astro.build/en/guides/images/#images-in-astro-files
- https://docs.astro.build/en/recipes/dynamically-importing-images/

**Comment by Benjamin-Frost** [comment]
See #304

**Pull request closed without merging**
